name: FreqTalk Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Generate Boilerplate
        run: flutter create --platforms=android .
      - run: flutter pub get
      - run: flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: freqtalk-android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Generate Boilerplate
        run: flutter create --platforms=windows .
      - run: flutter pub get
      - run: flutter build windows --release
      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: freqtalk-windows-exe
          path: build/windows/runner/Release/
